apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-map
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db-service:5432/user-db
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: admin
  SPRING_JPA_HIBERNATE_DDL_AUTO: none