CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    additional_info VARCHAR(255),
    average_rating FLOAT(53),
    title VARCHAR(255),
    won BOOLEAN,
    year_of_award VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE movie_category (
    movie_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (movie_id, category_id)
);

CREATE TABLE movie_users_ratings (
    rating FLOAT(24) NOT NULL,
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    PRIMARY KEY (movie_id, user_id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    api_key VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IDXo6ifx5x4vtwfrpu1a42l8u81w ON MOVIE (TITLE);

ALTER TABLE IF EXISTS movie_category ADD CONSTRAINT FKhkem46gi7yq1019e1j8hlvp9y FOREIGN KEY (category_id) REFERENCES category;

ALTER TABLE IF EXISTS movie_category ADD CONSTRAINT FKdhlw8bp2rx2bhkp1orkg12lor FOREIGN KEY (movie_id) REFERENCES movie;

ALTER TABLE IF EXISTS movie_users_ratings ADD CONSTRAINT FKesd9u0lk8kk31hh2jk7v6135i FOREIGN KEY (movie_id) REFERENCES movie;

ALTER TABLE IF EXISTS movie_users_ratings ADD CONSTRAINT FKo7eh118x6p810tcdtekvnq3gx FOREIGN KEY (user_id) REFERENCES users;