name: CI-qa-service

on:
  push:
    branches:
      - main
    paths:
      - 'qa-service/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('qa-service/**/pom.xml') }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build qa-service
        run: mvn clean install -Dmaven.test.skip --file qa-service/pom.xml

      - name: Publish JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: qa-service-jar
          path: qa-service/target/qa-service-0.0.1-SNAPSHOT.jar

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: qa-service-jar
          path: qa-service/target

      - name: Build Container image
        run:  IMAGE_TAG=latest docker-compose build qa-service

      - name: Tag image to push to docker hub
        run: docker tag qa-service-image ${{ secrets.DOCKER_USERNAME }}/qa-service-image

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/qa-service-image